
```{r}
install.packages("swirl") #BIS180L students do not need to this.
library(swirl)
swirl()
```

```{r}
##1. Basic Building blocks
x <- 5+7
x
y <- x-3
y
z <- c(1.1, 9, 3.14) #vector
z
c(z, 555, z)
z*2 + 100
#x^2 means 'x squared'. To take the square root, use the sqrt() function and to take the absolute value, use the abs() function.
my_sqrt <- sqrt(z - 1)
my_sqrt
my_div <- z/my_sqrt
my_div
c(1, 2, 3, 4) + c(0, 10)
c(1, 2, 3, 4) + c(0, 10, 100)
z*2 + 1000
my_div
```

```{r}
##3. Sequences of Numbers
1:20
pi:10
15:1
seq(1, 20)
seq(0, 10, by=0.5)
seq(5, 10, length=30)
my_seq <- seq(5, 10, length=30)
#to know the length of the vector
length(my_seq)
1:length(my_seq)
seq(along.with = my_seq)
seq_along(my_seq)
rep(0, times = 40) #create a vector that has 40 zeros
rep(c(0, 1, 2), times = 10) #10 repetitions of the vector (0,1,2)
rep(c(0, 1, 2), each = 10) #10 zeros, 10 ones, and 10 twos
```

```{r}
## Vectors
num_vect <- c(0.5, 55, -10, 6)
tf <- num_vect < 1
tf #4 logical values
num_vect >= 6 #`==` for exact equality, and `!=` for inequality
my_char <- c("My", "name", "is")
my_char
paste(my_char, collapse = " ")
my_name <- c(my_char, "Xiaolu")
my_name
paste(my_name, collapse = " ")
paste("Hello", "world!", sep = " ")
paste(1:3, c("X", "Y", "Z"), sep = "") #will loop if different length?
paste(LETTERS, 1:4, sep = "-")
```

```{r}
#5. Missing Values
x <- c(44, NA, 5, NA)
x*3
y <- rnorm(1000)
z <- rep(NA, 1000)
my_data <- sample(c(y, z), 100)
my_na <- is.na(my_data)
my_na
my_data == NA
sum(my_na)
my_data
0/0
Inf - Inf
```

```{r}
## 6. Subsetting Vectors
x
x[1:10]
x[is.na(x)]
y <- x[!is.na(x)]
y
y[y > 0]
x[x > 0]
x[!is.na(x) & x > 0] #x that are both non-missing AND greater than zero
x[c(3, 5, 7)]
x[0]
x[3000]
x[c(-2,-10)] #exclude 2nd and 10th elements
x[-c(2,10)]
vect <- c(foo = 11, bar = 2, norf = NA)
vect
names(vect)
vect2 <- c(11, 2, NA)
names(vect2) <- c("foo", "bar", "norf")
identical(vect, vect2)
vect["bar"] #get the element named "bar"
vect[c("foo", "bar")]
```

```{r}
## 7. Matrices and Data Frames
my_vector <- 1:20 #don't need c() when using ':' for example c(1, 2, 3) or 1:3
my_vector
dim(my_vector)
length(my_vector)
dim(my_vector) <- c(4,5) #give it a dimension
dim(my_vector)
attributes(my_vector)
my_vector
class(my_vector)
my_matrix <- my_vector
my_matrix2 <- matrix(my_vector, 4, 5)
identical(my_matrix, my_matrix2)
patients <- c("Bill", "Gina", "Kelly", "Sean")
cbind(patients, my_matrix)
my_data <- data.frame(patients, my_matrix)
my_data
class(my_data)
cnames <- c("patient", "age", "weight", "bp", "rating", "test")
colnames(my_data) <- cnames
my_data
```

```{r}
## 8. Logic
TRUE == TRUE
(FALSE == TRUE) == FALSE
6 == 7
6 < 7
10 <= 10
5 != 7
!5 == 7
FALSE & FALSE # '&' evaluates avross a vector; `&&` version of AND only evaluates the first member of a vector
TRUE & c(TRUE, FALSE, FALSE)
TRUE | c(TRUE, FALSE, FALSE)
TRUE || c(TRUE, FALSE, FALSE)
5 > 8 || 6 != 8 && 4 > 3.9
```

```{r}
## 9. Functions
Sys.Date()
mean(c(2, 4, 5))
boring_function <- function(x) {
  x
}
boring_function('My first function!')
boring_function()
my_mean(c(4, 5, 10))
```

```{r}
## 12. Looking at Data
ls()
class(plants)
dim(plants)
nrow(plants)
ncol(plants)
object.size(plants)
names(plants)
head(plants)
head(plants, 10)
tail(plants, 15)
summary(plants)
table(plants$Active_Growth_Period)
str(plants)
```